hydra:
  run:
    dir: process/outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.name}
  sweep:
    dir: process/outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  name: "test"
  random_ratio: 0.5
  sample_ratio: 1.0
  rank: 5

model:
  name: "pytorch_classification"
  num_rank: 10

training:
  seed: 42
  valid_batch_size: 16
  epochs: 8
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.001
  
  train_loader:
    batch_size: 32
    shuffle: True
    num_workers: 4
    pin_memory: True
  valid_loader:
    batch_size: 16
    shuffle: False
    num_workers: 4
    pin_memory: True


mlflow:
  experiment_name: "classification"
