hydra:
  run:
    dir: process/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.name}

data:
  name: "test"

model:
  name: "tlearner"
  num_rank: 10

training:
  classifier:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: 0
  regressor:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: 0

mlflow:
  experiment_name: "biased_data"
