hydra:
  run:
    dir: process/outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.name}
  sweep:
    dir: process/outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  name: "test"
  random_ratio: 0.5
  rank: 5

model:
  name: "tlearner"
  num_rank: 10
  sample_ratio: 1.0

training:
  classifier:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: -1
  regressor:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: -1

mlflow:
  experiment_name: "biased_data"
