hydra:
  run:
    dir: process/outputs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.name}
  sweep:
    dir: process/outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  name: "test"
  sample_ratio: 1.0

model:
  name: "tlearner"
  num_rank: 10

training:
  classifier:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: 0
  regressor:
    importance_type: "gain"
    random_state: 42
    force_col_wise: True
    n_jobs: -1
    verbosity: 0

mlflow:
  experiment_name: "base_pattern"
