name: Lints

on:
  push:
  pull_request: {}

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --progress-bar off -U poetry
          poetry install
      
      - name: Run Ruff (lint)
        run: ruff check --output-format=github --exclude "scripts" .
      