name: Lints

on:
  push:
  pull_request: {}

jobs:
  lints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --progress-bar off -U poetry
          poetry env use 3.11
          poetry install
      
      - name: Run Ruff (lint)
        run: poetry run ruff check --output-format=github --exclude "dev" .
    
      - name: Run Mypy (type check)
        run: poetry run mypy --config-file pyproject.toml . --output-format=github

      - name: Run Pytest (unit test)
        run: poetry run pytest  tests
      